#!/bin/sh /etc/rc.common
# Copyright (C) 2023 @lmahmutov

USE_PROCD=1
START=99
STOP=15

start_service()
{
    procd_open_instance
    procd_set_param command /bin/sh "/etc/config/mqtt-ha.sh"
    procd_close_instance
}


stop_service()
{
      kill $(ps | grep mosquitto_sub | head -1 | awk '{print $1}')
}

restart_service() {
        stop
	sleep 2
        start
}